name: Selenium E2E Tests

on:
  schedule:
    - cron: "0 12 * * 1-5"  # Runs at noon (12:00 UTC) from Monday to Friday
  workflow_dispatch:  # Allows manual execution

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your dependencies from the requirements file

      # Install Google Chrome and ChromeDriver
      - name: Install Google Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget curl unzip
          curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
          sudo dpkg -i google-chrome.deb
          sudo apt --fix-broken install -y

      # Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | sed 's/\./\-/g')
          DRIVER_VERSION=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run Selenium Tests
        run: python run_tests.py --maxfail=1 --disable-warnings
        env:
          DISPLAY: ":99.0"  # Needed for running headless browsers in CI

      - name: Upload failure screenshots (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-failure-screenshots
          path: ./screenshots
