name: Selenium E2E Tests

on:
  schedule:
    - cron: "0 12 * * 1-5"  # Runs at noon (12:00 UTC) from Monday to Friday
  workflow_dispatch:  # Allows manual execution

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your dependencies from the requirements file

      # Install Google Chrome and ChromeDriver
      - name: Install Google Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable
          
      - name: Run Selenium Tests
        run: python run_tests.py --maxfail=1 --disable-warnings
        env:
          DISPLAY: ":99.0"  # Needed for running headless browsers in CI

      - name: Upload failure screenshots (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-failure-screenshots
          path: ./screenshots
